<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Amanda Chen">
<meta name="author" content="David Hagmann">
<meta name="keywords" content="Gender difference, Advice, Interpresonal relationship">
<meta name="description" content="FLATTERING ADVICE">

<title>Flattering Advice: Avoiding Disappointment in Advice-Giving</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="manuscript_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript_files/libs/quarto-html/quarto.js"></script>
<script src="manuscript_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="manuscript_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript_files/libs/bootstrap/bootstrap-61c9f5fe3bf7f1d5f9219c551e9df0c2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="manuscript_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="manuscript_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="_extensions/wjschne/apaquarto/apa.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#open-science-statement" id="toc-open-science-statement" class="nav-link" data-scroll-target="#open-science-statement">Open Science Statement</a></li>
  <li><a href="#study-1" id="toc-study-1" class="nav-link" data-scroll-target="#study-1">Study 1</a>
  <ul class="collapse">
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul></li>
  <li><a href="#study-2" id="toc-study-2" class="nav-link" data-scroll-target="#study-2">Study 2</a>
  <ul class="collapse">
  <li><a href="#methods-1" id="toc-methods-1" class="nav-link" data-scroll-target="#methods-1">Methods</a></li>
  <li><a href="#results-1" id="toc-results-1" class="nav-link" data-scroll-target="#results-1">Results</a></li>
  <li><a href="#discussion-1" id="toc-discussion-1" class="nav-link" data-scroll-target="#discussion-1">Discussion</a></li>
  </ul></li>
  <li><a href="#study-3" id="toc-study-3" class="nav-link" data-scroll-target="#study-3">Study 3</a>
  <ul class="collapse">
  <li><a href="#methods-2" id="toc-methods-2" class="nav-link" data-scroll-target="#methods-2">Methods</a></li>
  <li><a href="#results-2" id="toc-results-2" class="nav-link" data-scroll-target="#results-2">Results</a></li>
  <li><a href="#discussion-2" id="toc-discussion-2" class="nav-link" data-scroll-target="#discussion-2">Discussion</a></li>
  </ul></li>
  <li><a href="#general-discussion" id="toc-general-discussion" class="nav-link" data-scroll-target="#general-discussion">General Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="manuscript.pdf"><i class="bi bi-file-pdf"></i>PDF (apaquarto)</a></li><li><a href="manuscript.docx"><i class="bi bi-file-word"></i>MS Word (apaquarto)</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">




<br>

<br>

<section id="title" class="level1 title unnumbered unlisted">
<h1 class="title unnumbered unlisted">Flattering Advice: Avoiding Disappointment in Advice-Giving</h1>
<div class="Author">
<br>

<p>Amanda Chen and David Hagmann</p>
<p>Department of Management, The Hong Kong University of Science and Technology</p>
</div>
</section>
<section id="author-note" class="level1 unnumbered unlisted AuthorNote">
<h1 class="unnumbered unlisted AuthorNote">Author Note</h1>
<p>Amanda Chen <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" id="orchid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> http://orcid.org/0000-0002-4428-627X</p>
<p>David Hagmann <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" id="orchid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> http://orcid.org/0000-0002-2080-997X</p>
<p>The authors are grateful to XXX for their helpful comments.</p>
<p>Correspondence concerning this article should be addressed to Amanda Chen, Department of Management, The Hong Kong University of Science and Technology, Hong Kong, Email: zchengj@connect.ust.hk</p>
</section>
<section id="abstract" class="level1 unnumbered unlisted AuthorNote">
<h1 class="unnumbered unlisted AuthorNote">Abstract</h1>
<div class="AbstractFirstParagraph">
<p>Good advice improves decision quality but often requires delivering unpleasant truths that may disappoint advisees. Across three pre-registered and incentivized experiments involving real adviser-advisee interactions (N = 3,900), we show that advisers prioritize avoiding disappointment at the expense of accuracy and their own earnings. In Study 1, advisers financially rewarded for accuracy still tailor recommendations to aspirational goals expressed by advisees, resulting in worse advice. When incentivized to be liked, advisers provide even more flattering advice, and advisees reward this by rating these advisers as more likable, despite the advice being less honest and less accurate (Study 2). The desire to avoid disappointment may lead to inequities if there are differences in expectations across social groups. In Study 3, we examine a setting in which men expect to perform better than women. We show that advisers take into account these expectations, leading to systematically different advice for men and women even when their gender is unknown to advisers. Advisers’ efforts to avoid disappointment may thus contribute to systematic gender disparities in advice, with implications for downstream decision-making.</p>
</div>
<p><em>Keywords</em>: Gender difference, Advice, Interpresonal relationship</p>
</section>
<section id="firstheader" class="level1 title unnumbered unlisted">
<h1 class="title unnumbered unlisted">Flattering Advice: Avoiding Disappointment in Advice-Giving</h1>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Career trajectories for men and women often differ substantially, even among those with similar qualifications. One source of such differences may be the advice that people receive. Prior work has documented that men receive more aspirational advice and women more risk-averse advice, which may explain why women are less likely to apply for and ultimately obtain more rewarding positions <span class="citation" data-cites="Kanze2018">(Kanze et al., 2018)</span>. Research on gender discrimination has focused on the role of unconscious bias <span class="citation" data-cites="Greenwald2009 Greenwald1995">(Banaji &amp; Greenwald, 1995; Nosek et al., 2009)</span>, but interventions that try to reduce this bias have been largely unsuccessful <span class="citation" data-cites="Chang2019 Paluck2009">(Chang et al., 2019; Paluck &amp; Green, 2009)</span>. Recent work has proposed cognitive, rather than unconscious, biases that can lead to gender discrimination through the formation of false beliefs <span class="citation" data-cites="Hagmann2024">(Hagmann et al., 2024)</span>. Here, we propose a novel source of differences in advice by drawing on recent work on belief-based utility, expectation-based reference points <span class="citation" data-cites="Koszegi2006 Koszegi2009">(Kőszegi &amp; Rabin, 2006, 2009)</span>, and the hedonic consequences of information <span class="citation" data-cites="Golman2017">(Golman et al., 2017)</span>.</p>
<p>Advice figures prominently in workplace and personal decision-making, shaping choices about promotions, career paths, and everyday dilemmas <span class="citation" data-cites="Gino2007 Harvey1997 Soll2009">(Gino &amp; Moore, 2007; Harvey &amp; Fischer, 1997; Soll &amp; Larrick, 2009)</span>. Its fundamental premise is to improve outcomes by enabling decision-makers to learn from others’ expertise. However, while honest advice can lead to better decisions, it can also lead to disappointment when it suggests a desired outcome is unlikely to materialize. Advisers may be motivated to offer flattering recommendations that align with advisees’ hopes, sparing them the disappointment of a more sobering forecast.</p>
<p>Advice with the potential for disappointment appears in diverse organizational settings: supervisors deliver feedback on employee performance, lawyers convey likely outcomes of litigation to their clients, and academics offer thoughts on colleagues’ manuscripts. Ideally, honest information would help people identify their strengths and weaknesses, make informed decisions about whether to pursue legal cases, and strengthen papers prior to submission to academic journals, thus improving long-term outcomes. In practice, however, interpersonal considerations may prevent candor. When someone’s expectations are (too) high, an adviser might hesitate to deliver information that undermines it—particularly if doing so risks negative interpersonal repercussions.</p>
<p>People often go to great lengths to avoid unpleasant information, deriving belief-based utility from maintaining favorable views of themselves <span class="citation" data-cites="Golman2017 Ho2018 Loewenstein2018">(Golman et al., 2017; Ho et al., 2021; Loewenstein &amp; Molnar, 2018)</span>. Moreover, they often prefer advisers who withhold bad news from them <span class="citation" data-cites="Shalvi2019">(Shalvi et al., 2019)</span> and punish those who communicate bad news <span class="citation" data-cites="John2019">(John et al., 2019)</span>. Advisers, anticipating these preferences and consequences face a dilemma: Should they provide the accurate but potentially painful truth, or shade their recommendations to preserve the advisee’s mood and the adviser’s own standing? Advisers who fear they will be blamed or disliked for undermining someone’s confidence may reasonably avoid candid feedback, particularly if they don’t incur a cost when the advisee makes a mistake.</p>
<p>In our experiments, however, advisees have no opportunity to punish the adviser, and advisers’ financial incentives are linked to the decisions the advisees make. We propose that advisers nonetheless have reason to provide flattering advise because they recognize the psychological toll of disappointing news. As a result, they may similarly incur a hedonic cost for delivering unpleasant information that they anticipate may distress the advisee. Thus, even in the anonymized context of an online experiment, we hypothesize (and find) that advisers are relucant to disappoint advisees and advice is thus biased upward, away from accuracy and toward confirming advisees’ priors. We show that this reduces the quality of advice—but that advisees nonetheless view flattering advisers more favorably.</p>
<p>We present the results of three preregistered experiments in which participants are paired anonymously as advisers and advisees. Advisers are incentivized to offer accurate advice, with bonus earnings depending on the outcome of an advisee’s decision. We study a setting in which advisees can communicate their expectations to an adviser, and experimentally manipulate whether advisers observe this expectation. Our design simulates organizational contexts where mentors and managers often have some sense of an employee’s confidence or aspirations and thus could adjust their feedback to avoid disappointing them. Interpersonal considerations would likely be stronger in situations in which the adviser and advisee have an existing relationship and when the advice is delivered face-to-face. Moreover, advisers usually do not suffer any direct costs when their flattering advice leads to a poor outcome for the recipient, particularly when it is not clear what would have happened under a counterfactual.^[In some cases, however, repeated interaction might also increase incentives for honest feedback. Someone who is known to persistently give overoptimistic advice may be viewed as less trustworthy in the long run.]</p>
<p>In Study 1, we nudge advisees into a preference for competing against either a group of top-performers or a group of low-performers, through the use of a default option. Advisers who observe the actual performance of advisees and therefore have the relevant information needed to make a recommendation nonetheless take into account the initial preference when recommending which group they should compete against. In Study 2, we ask advisees to upload photos of themselves and advisers rank them on their attractiveness. Advisers then recommend which rank the advisee should bet on, receiving an incentive either for the advisee’s accuracy or for being evaluated favorably. Both groups of advisers recommend a rank that is more attractive than what they themselves have evaluated the advisee, and those incentivized for likability further inflate the ranking. Advisees evaluate advisers more favorably when they recommend betting on a more attractive rank, including viewing them as more trustworthy.</p>
<p>In Study 3, we examine a setting in which participants report their expected performance on a mathematics quiz. Advisers observe the test-taker’s true score and, in one treatment, the score they guessed they would receive. They then recommend whether the advisee should compete against a group of high performers or low performers. Importantly, this “competition” is based on the past performance observed by the adviser and thus the advisee’s expectation does not provide instrumental information. However, we find that (1) men expect to perform better than women, given identical performance, and (2) advisers take these expectations into account. As a result, when expectations (but not gender) are known to advisers, the advice given to men and women differs, and men are more often advised to compete against the group of high performers. Notably, this leads to worse advice for men than for women.</p>
</section>
<section id="open-science-statement" class="level1">
<h1>Open Science Statement</h1>
<p>We report all manipulations, measures, and data exclusion in our experiments. The preregistration reports, screenshots of all experimental materials, and the analysis code to replicate all statistical analyses and figures are available on the Open Science Framework (<a href="https://osf.io/8r3d4/?view_only=5ad7bafcd16b4d4ba08bb28b0e2bd02d" class="uri">https://osf.io/8r3d4/?view_only=5ad7bafcd16b4d4ba08bb28b0e2bd02d</a>).</p>
</section>
<section id="study-1" class="level1">
<h1>Study 1</h1>
<p>We first examine whether advisers take into account the expectations of advisees when providing a recommendation. A group of participants (“Advisees”) complete a quiz consisting of ten questions that draw on ego-relevant domains. They then express a non-binding preference to compete against a group of high performers or low performers on the same task, based on their past performance. We nudge participants towards picking either the low or the high performer group by selecting one of the two by default. A second group of participants (“Advisers”) observe Advisees’ score on the quiz and, in one treatment, also which group they had selected. We predicted that Advisees who were nudged toward the high performer group would be more likely to receive advice to compete against this high group when Advisers observed their non-binding choice.</p>
<section id="methods" class="level2">
<h2 data-anchor-id="methods">Methods</h2>
<p>In a preliminary stage, we recruited 50 participants from Prolific and gave them five minutes to complete a quiz consisting of ten items. The quiz included word puzzles, identifying emotions from photos, and selecting the best responses for hypothetical scenarios. These questions were adapted from surveys that measure problem-solving, emotional intelligence, and communication skills—which we pre-tested as being important in modern society and hence where participants might have a stake in doing well. Participants received a bonus of five cents for each correctly answered question. We then ranked them based on their score and label the 20 participants with the lowest (highest) scores as the Low (High) Performer Group.</p>
<p>Next, we recruited 201 participants for the role of Advisees. They completed the same 10-item quiz, also earning five cents for each correct answer. We then asked them to express a non-binding preference for whether they would like to compete against the High or Low Performer Group. We informed them that they would be invited back at a later date when they could make a binding decision and they could earn a bonus based on whether their score on this quiz was equal to or higher than a randomly selected member from their comparison group. If they picked the High Performer Group and had an equal or higher score than a randomly selected member of that group, they would earn a bonus of 50 cents. If they picked the Low Performer Group and outperformed a randomly selected member of that group, they could earn a bonus of 20 cents. If their score was lower in this comparison, they would not earn an additional bonus. We randomized which of the two groups (High or Low Performers) was selected by default, and Advisees were free to select the other group. They also made a guess as to their score, and the survey concluded with basic demographic questions.</p>
<p>We then recruited 1,000 participants for the role of Advisers, and the focal part of our experiment. They were informed of the ability quiz that the Advisees had completed, how the Low Performer Group and High Performer Groups were constructed, as well as the choice and incentives for the Advisees. We then asked Advisers to give advice to ten participants on which group they should compete against. Advisers were randomly assigned to one of two treatments. In the “Performance” treatment, they observed only the score of the other participant. In the “Performance + Expectation” treatment, they additionally observed the advisee’s non-binding choice of which group to compete against. However, since the outcome was based solely on the past quiz score and advisers, but not advisees, know the score, this initial choice was not informative for the purpose of recommending competing against one group or the other. Advisers could earn the same bonus as one of the participants they had given advice to and who returned to make a decision. The survey concluded with basic demographic questions.</p>
<p>Finally, we invited Advisees back for the follow-up survey. Following our preregistration, we kept the survey open for 7 days. In total, 176 Advisees returned. The short survey reminded them of the task they completed in the previous survey, informed them that other participants from Prolific had observed their real score and given them advice on which group to compete against, and finally reminded them of how many questions they guessed they had answered correctly. They were not informed of their true score or the score of the groups they could compete against. Participants then observed the advice from a randomly selected adviser and made their decision.</p>
</section>
<section id="results" class="level2">
<h2 data-anchor-id="results">Results</h2>
<p>We begin by examining the performance of the Stage 1 participants. Because our default treatment takes place after participants completed the ability quiz, we do not expect a difference in performance across the Low and High Default treatments. Indeed, the two groups scored no different from one another (5.1 and 5.18 for the Low Default and High Default treatments, respectively, <span class="math inline">t(199) = 0.31</span>, <span class="math inline">p = .756</span>). The default manipulation affected their initial choices. In the “Low Default” treatment, only 22% of participants initially preferred competing against the High Performer Group, compared to 65% of participants who saw the High Performer Group highlighted (<span class="math inline">\chi^2</span>(1, n = 201) = 36.62, p &lt; .001).</p>
<div class="cell FigureWithoutNote" data-layout-align="center" prefix="" data-tblnum="1" data-custom-style="FigureWithoutNote">
<div id="tbl-study1regs" class="cell quarto-float quarto-figure quarto-figure-center" data-layout-align="center" prefix="" data-tblnum="1">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-study1regs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Advice to compete against the High Performer Group in Study 1. Displaying the non-binding choice of those for whom the Low Performer Group was selected by default makes it more likely that they are advised to compete against the High Performer Group (Column 1). Column 2 restricts the analysis to advisers who observed advisees’ initial non-binding choice and controls for advisees’ score on the quiz. Standard errors are clustered at the adviser level.</p>
</div>
</figcaption>
<div aria-describedby="tbl-study1regs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High Default</td>
<td style="text-align: center;">0.011</td>
<td style="text-align: center;">0.025*</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.013)</td>
<td style="text-align: center;">(0.011)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expectation Shown</td>
<td style="text-align: center;">−0.041*</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.016)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expectation x High Default</td>
<td style="text-align: center;">0.037+</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.019)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Performance</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.168***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.004)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: center;">0.389***</td>
<td style="text-align: center;">−0.503***</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.012)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.020)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: center;">10000</td>
<td style="text-align: center;">5000</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>We now examine whether advisers took the advisees’ expectations into account. Recall that advisees who were defaulted to competing against the High Performer Group were indeed more likely to choose this group, which, from the advisers’ perspective, could signal high confidence in their abilities. Our theory predicts that showing expectations should lead to more flattering advice— specifically, a recommendation to compete against the High Performer Group— for advisees with a high default choice compared to those with a low default choice. Column 1 of <a href="#tbl-study1regs" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a> reports a linear probability model with advice to compete against the high group as the outcome measure, incorporating the default choice advisees saw, whether expectations were shown to the adviser, and the interaction of the two. Because each adviser made ten recommendations, we cluster standard errors at the adviser level. As predicted, we find a marginally significant interaction effect: advisees with a default choice to compete against the High Performer Group (nudged to have high expectations, though not necessarily holding them) were more likely to receive advice to compete against stronger competitors when their expectations were shown compared to when they were hidden. We reported a linear probability model on advising to compete against the High Performer group for advisers in the “Expectations” treatment, controlling for the true performance of the advisee in Column 2 of <a href="#tbl-study1regs" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a>. We observe a significant main effect of the default treatment, where a high default increased the likelihood of receiving flattering advice. It is worth noting that, since only 65 % of advisees in the high default group actually stuck with their default choice, this represents a conservative test of the effect of high expectations on the likelihood of receiving flattering advice.</p>
</div>
<div class="cell FigureWithoutNote" data-layout-align="center" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-study1Advice" class="quarto-float quarto-figure quarto-figure-center" data-fignum="1" prefix="" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-study1Advice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Advisees who were nudged to express high expectations were more likely to receive advice to compete against the High Performer Group.</p>
</div>
</figcaption>
<div aria-describedby="fig-study1Advice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-study1Advice-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="discussion" class="level2">
<h2 data-anchor-id="discussion">Discussion</h2>
<p>When the quality of a decision does not depend on someone’s expectations, the adviser’s awareness of the advisee’s expectations should not influence the advice given. However, in line with our argument that advisers take into account the belief utility of the advisee and prefer to flatter rather than disappoint, we find that displaying the advisee’s expectations does make a difference. Specifically, advisees who expressed a preference for stronger competitors were more likely to receive ‘flattering’ advice, encouraging them to pursue that option. One possible explanation for this finding is that, rather than trying to flatter, advisers may simply be telling advisees what they want to hear. In the next study, we aim to investigate the mechanism behind this discrepancy in advice-giving when expectations are revealed, exploring the question: Why do people give flattering advice?</p>
</section>
</section>
<section id="study-2" class="level1">
<h1>Study 2</h1>
<p>So far, we have shown that displaying expectations influences the advice given. Specifically, advisers were more likely to recommend competing against a group of high performers to advisees with higher performance expectations compared to those without. We now directly test whether this effect is driven by interpersonal concerns. In particular, we explore whether more flattering advice stems from a desire to be liked, and whether advisees, in turn, like advisers more when they receive flattering advice.</p>
<p>We conducted a three-stage experiment in which we experimentally manipulated the incentives for advisers. We began by inviting a group of advisees to upload photos of themselves (“selfies”) and informed them that they would be rated on their attractiveness. We grouped them with nine other participants of the same gender and recruited participants of the opposing gender to rank them from most to least attractive and to provide advice. Specifically, we asked them to advise the participant they ranked as the 7th most attractive (4th least attractive) on what rank they should bet they were ranked by a larger group of raters. Advisers were randomly assigned to two treatments, receiving a bonus payment either if the advisee guessed their rank accurately or if the advisee evaluated the adviser as likeable as measured by an unincentivized scale response. We hypothesize that advisers who want to be liked by advisees will recommend that they bet on a lower rank, i.e. that they are more attractive.</p>
<section id="methods-1" class="level2">
<h2 data-anchor-id="methods-1">Methods</h2>
<p>We recruited 300 participants from Prolific and, after asking demographic questions, invited them to upload photos of themselves (selfies) to be rated by other participants on attractiveness. 100 men and 107 women agreed to do so and uploaded pictures that adhered to our instructions (e.g., did not include other people). We selected the first 100 photos from women to arrive at a gender-balanced sample (<span class="math inline">M_{\text{Age}}</span> = 39.37 years). Participants were informed that their selfies would be randomly grouped with those of nine other participants of their gender and ranked in terms of attractiveness by a group of new Prolific participants of the opposite gender. Lastly, they guessed their rank (unincentivized).</p>
<p>Next, we recruited a new, gender-balanced sample for the role of advisers. 472 participants from Prolific (<span class="math inline">M_{\text{Age}}</span> = 41.0275424 years; 49.79% Female) started by providing demographic information, then were matched to a group of the opposite gender. They then ranked participants from most to least attractive using a drop-down menu next to each picture. Because of a limitation with the survey software, participants were able to select the same rank for multiple participants, rather than rank them uniquely. We remove 115 participants who did not follow instructions and provide a unique ranking.</p>
<p>After submitting their ratings, they saw the photo of the participant they had ranked as the 7th most attractive (i.e., the 4th least attractive). They were reminded of the rank they had given to that person and informed that this participant would be invited back and could earn a $1 bonus if they guessed their rank correctly. The rank was determined by the aggregate ratings of all participants who had ranked this group. Their task was to give advice to this participant about the rank they should bet on based on having observed all ten selfies and their own assessment. We randomly assigned participants to one of two incentivization schemes. In the “Accuracy” treatment, they received a bonus identical to the advisee: $1 if they guessed their rank correctly. In the “Likeability” treatment, we informed them that they would be rated by the advisee on a 5-point Likert scale for how likeable they thought they were. Each point on the scale would translate to a bonus of 20 cents. They then selected a rank that they would recommend the advisee to bet on.</p>
<p>Finally, we invited participants from Stage 1 and were ranked as the 7th attractive by at least one adviser (so that they received advice) back for the follow-up survey. Following our preregistration, we kept the survey open for 7 days. In total, 146 participants (77 men, 69 women) returned. They were reminded of the selfie they uploaded in Stage 1 and informed that a group of 10 selfies, including theirs, had been rated by other participants from Prolific. They then saw the advice from a randomly selected adviser and made their estimate with a $1 incentive for guessing accurately. They then saw the rank they had been advised to bet on one more time and were asked to rate the adviser’s likability, warmth, friendliness, good-naturedness, trustworthiness, and sincerity on 5-point Likert scales (adapted from <span class="citation" data-cites="Fiske2007">Fiske et al. (2007)</span>).</p>
</section>
<section id="results-1" class="level2">
<h2 data-anchor-id="results-1">Results</h2>
<div class="cell FigureWithoutNote" data-layout-align="center" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-study2advice" class="quarto-float quarto-figure quarto-figure-center" data-fignum="2" prefix="" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-study2advice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Advisers were asked to suggest what rank to bet on for someone they ranked as the 7th most attractive out of ten people. When incentivized for accuracy, most of them advised betting on 7, which was based on their evaluation of the recipient’s attractiveness. However, when incentivized for likability, many participants gave flattering advice by suggesting betting on higher ranks that imply a higher evaluation of attractiveness.</p>
</div>
</figcaption>
<div aria-describedby="fig-study2advice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-study2advice-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
</figure>
</div>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>We begin by examining the prior beliefs of advisees who uploaded their selfies. On average, men guessed they ranked 5.76 in their group of 10 and women guessed that they ranked 6.37. Participants overall underestimate their attractiveness relative to the benchmark average of 5.5. Moreover, women do so more than men <span class="math inline">t(205) = 2.15</span>, <span class="math inline">p = .033</span>. Notably, people’s self-perceptions correlated strongly with the aggregate ratings of the advisers (0.43, <span class="math inline">t(193) = 6.70</span>, <span class="math inline">p &lt; .001</span>). However, there was substantial heterogeneity in perceptions of attractiveness. Of the 200 participants, 149 were ranked as 7th most attractive by at least one adviser. On average, men in this subset estimated they were ranked 5.94th and women estimated they were ranked 6.59th (<span class="math inline">t(143) = 1.94</span>, <span class="math inline">p = .054</span>).</p>
</div>
<p>Next, we turn our attention to the advisers (<a href="#fig-study2advice" class="quarto-xref" aria-expanded="false">Figure&nbsp;2</a>). In the Accuracy condition, those uploading selfies were advised to bet on rank 6.19. Notably, this is significantly more attractive than the 7th rank those advisers had themselves guessed just on the prior screen (<span class="math inline">t(234) = -8.82</span>, <span class="math inline">p &lt; .001</span>). This suggests that even when incentivized for accuracy, participants offered flattering advice.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Importantly, and as predicted, we find that advisers in the Likeable treatment recommend betting on a lower rank, communicating that they think the participant in the selfie is more attractive (5.38, <span class="math inline">t(470) = 5.44</span>, <span class="math inline">p &lt; .001</span>). This suggests that advisers inferred that advising someone that they were more attractive would make the adviser appear more likeable and therefore provided advice that communicated a more favorable impression of the participants’ attractiveness. The distribution shown in <a href="#fig-study2advice" class="quarto-xref" aria-expanded="false">Figure&nbsp;2</a> shows that participants do not simply tell participants that they are the most attractive person in the group. They may infer that flattering advise needs to be somewhat realistic to be believable. We return to this in the general discussion.</p>
<!-- David: Making a note here that we should be sure to discuss this at the end -->
<!-- as something for future research. -->
<!-- David: We should also report something on accuracy of the advice given across -->
<!-- the treatments. Even if no difference. -->
<div class="cell FigureWithoutNote" data-layout-align="center" prefix="" data-tblnum="2" data-custom-style="FigureWithoutNote">
<div id="tbl-study2regs" class="cell quarto-float quarto-figure quarto-figure-center" data-layout-align="center" prefix="" data-tblnum="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-study2regs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>When individuals receive advice that implies a high level of attractiveness (lower rank), they tend to perceive the advice giver as more likable (Column 1), warm (Column 2). Column 3 shows that advisors are rated as more trustworthy when they advice lower ranks, but this relationship is only directional.</p>
</div>
</figcaption>
<div aria-describedby="tbl-study2regs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(2)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Advised Rank</td>
<td style="text-align: center;">−0.109*</td>
<td style="text-align: center;">−0.133**</td>
<td style="text-align: center;">−0.054</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.046)</td>
<td style="text-align: center;">(0.044)</td>
<td style="text-align: center;">(0.042)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: center;">3.777***</td>
<td style="text-align: center;">3.903***</td>
<td style="text-align: center;">3.397***</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.279)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.266)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.257)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: center;">146</td>
<td style="text-align: center;">146</td>
<td style="text-align: center;">146</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>Finally, we examine whether flattering advice indeed leads to more positive evaluations of advisers, or whether flattering advice is dismissed as insencere. Following our preregistration, we average the ratings on likeability, warmth, friendliness, and good-naturedness to create a scale of likeability (<span class="math inline">\alpha</span> = 0.9243334); and we create a scale of trustworthiness by averaging the ratings of trustworthiness and sincerity (<span class="math inline">\alpha</span> = 0.8740347).</p>
</div>
<div class="cell FigureWithoutNote" data-layout-align="center" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-study2rating" class="quarto-float quarto-figure quarto-figure-center" data-fignum="3" prefix="" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-study2rating-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Participants tend to rate advisors who suggest betting on a higher rank (implying greater attractiveness) as more likable and warm.</p>
</div>
</figcaption>
<div aria-describedby="fig-study2rating-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-study2rating-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
</figure>
</div>
</div>
</div>
<div class="cell FigureWithoutNote" data-layout-align="center" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-study2ratingByGroup" class="quarto-float quarto-figure quarto-figure-center" data-fignum="4" prefix="" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-study2ratingByGroup-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;4</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>After participants received advice that suggested betting on a rank that was lower than, equal to, or higher than their self-expectations, they evaluated advisors based on their likability and warmth. Participants rated advisors who gave flattering advice and delivered a high evaluation of their attractiveness as more likable and warm than those whose advice implied a lower evaluation of their attractiveness.</p>
</div>
</figcaption>
<div aria-describedby="fig-study2ratingByGroup-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-study2ratingByGroup-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
</figure>
</div>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>As seen in <a href="#fig-study2rating" class="quarto-xref" aria-expanded="false">Figure&nbsp;3</a>, we found that advisees who suggested that the advisee was more attractive (lower rank) were indeed rated as more likeable and warm (b = -0.109, p &lt; .05; b = -0.133, p &lt; .001, respectively; See Columns 1 and 2 of <a href="#tbl-study2regs" class="quarto-xref" aria-expanded="false">Table&nbsp;2</a>). When using their self-expectations as a reference point, advisors who suggest a rank lower than that point are perceived as less likable and warm (see <a href="#fig-study2ratingByGroup" class="quarto-xref" aria-expanded="false">Figure&nbsp;4</a>). Interestingly, these benefits are not at the cost of being hypocritical; advisers who recommend a more favorable rank are viewed as no less trustworthy (Column 3 of <a href="#tbl-study2regs" class="quarto-xref" aria-expanded="false">Table&nbsp;2</a>).</p>
</div>
<p>We were not powered to do a comparison across the two experimental groups and did not preregister such a difference. Indeed, we find no difference in likeability and warmth across the two treatments (<span class="math inline">t(144) = 1.09</span>, <span class="math inline">p = .275</span>, and <span class="math inline">t(144) = 0.58</span>, <span class="math inline">p = .562</span>, respectively). We also assess the quality of advice by measuring the discrepancy between the advised rank and the final rank. Our analysis revealed no significant difference between the two treatments in terms of how helpful the advice was for advisees in making accurate guesses, <span class="math inline">t(144) = -0.29</span>, <span class="math inline">p = .776</span>.</p>
</section>
<section id="discussion-1" class="level2">
<h2 data-anchor-id="discussion-1">Discussion</h2>
<p>In another context where advice communicates ego-relevant information (here, people’s attractiveness), we find that the advice people give is contingent on their incentives. Specifically, when they get rewarded for being more likeable, they recommend that the advisee bet on a more favorable rank than when they are incentivized for accuracy. Importantly, advisees do not discount flattering advice and instead evaluate people who advise them to bet on a more attractive rank as warmer and more likeable. These gains to interpersonal perceptions do not come at the cost of trustworthiness, even when the advice is substantially inflated (e.g., a recommendation that the advisee is the most attractive in the group).</p>
</section>
</section>
<section id="study-3" class="level1">
<h1>Study 3</h1>
<p>In Study 3, we replicate the main effect in a different ego-relevant domain: intelligence. The experimental design is conceptually identical to Study 1, but this time we utilize a more direct measure of expectation by asking participants to estimate their scores.</p>
<p>This three-stage experiment begins with measuring actual performance. Participants are then anchored to low or high performance expectations and asked to guess how many questions they answered correctly. As in previous studies, we recruit advisers who are presented with either just the advisee’s true performance or both the true performance and the number of questions the advisee believes they answered correctly. Advisers are then asked to provide advice on choosing a competitor. Finally, we present the advice to the advisees and ask them to make their final choice. Our key hypotheses are: (1) advisees anchored to high expectations will be more likely to receive advice to compete against the high-performing group, and (2) men will be more likely than women to be advised to compete against the high-performing group when expectations are disclosed.</p>
<section id="methods-2" class="level2">
<h2 data-anchor-id="methods-2">Methods</h2>
<p>We begin by first recruiting a sample of 50 participants from Prolific to complete a 10-question multiple choice mathematics quiz. The questions were taken from a paper-version of the ASVAB standardized exam, such that answers were not available online. Participants had five minutes to answer the quiz and were paid 10 cents for each correctly answered question. Like before, we define top 20 scores as “High Performers” and the bottom 20 scorers as the “Low Performers.” On average, participants answered 4.42 questions correctly, High Performers scored between 5 and 10, and Low Performers scored between 0 and 3. In order to anchor the expectations of participants in our main experiment, we simulated 1,000 pairings of groups of five participants, with the 5<sup>th</sup> percentile of groups scoring an average of 2.6 and the 95 th percentile scoring an average of 6.4. We report these averages to participants in the Low Expectations and High Expectations treatment, respectively.</p>
<p>We then recruited 1,002 participants for the role of advisees in Stage 1 of our main experiment. To arrive at a gender-balanced sample, we dropped the last two male participants to complete the survey, ending up with a sample of 500 men and 500 women (<span class="math inline">M_{\text{Age}}</span> = 42.16). Participants completed the same 10-item mathematics quiz as the earlier participants and were informed that their performance would affect their bonus earnings in a follow-up stage to be conducted a few days later. After completing the quiz, we informed them of the average score of a group of five participants from the preliminary survey. We randomly assigned them to learn about the 5<sup>th</sup> percentile of groups, which scored 2.6. (“Low Expectations” treatment) or the 95<sup>th</sup> percentile of groups, which scored 6.4 (“High Expectations” treatment). Participants then made a guess (unincentivized) about how many questions they think they answered correctly. The survey concluded with basic demographic questions.</p>
<p>We then recruited 1,000 participants for Stage 2, placing them in the role of advisers. We began by informing them of the mathematics quiz that participants in the preliminary study and Stage 1 had completed, and informed them of the average score of all participants in the preliminary study. Advisers had to recommend whether an advisee should compete against the Low Performers or the High Performers (we used these terms in the survey). We anticipated that being told to compete against High Performers is more flattering and hence being told to compete against the Low Performers would be disappointing if one had expected to do well. Advisees could earn a bonus if their score was equal to or higher than that of a randomly selected member from their chosen group. Competing against the High Performers was more challenging, resulting in an average bonus of 50 cents, compared to 30 cents when competing against other groups.</p>
<p>Like before, advisers were randomly assigned to one of two treatments. In the “Baseline” treatment, they only observed the score of the advisee on the mathematics quiz. In the “Expectation” treatment, they observed the score as well as the advisee’s guess for how many questions they answered correctly. We want to emphasize that sice the outcome is determined only by the past score on the quiz, the advisee’s guess is immaterial to which group they should compete against. Moreover, in neither treatment did they receive any demographic information about their advisee. Participants gave recommendations to 10 advisees, which unbeknownst to them were five men and five women matched to have identical performance on the test.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> They were informed that if their advice was shown to a participant who returned for the follow-up survey, they would receive the identical bonus as that participant. The survey then concluded with basic demographic questions.</p>
<p>Finally, we invited participants from Stage 1 back for the follow-up survey. Following our preregistration, we kept the survey open for 7 days. In total, 951 participants (481 men, 470 women) returned. The brief survey reminded them of the task they completed in Stage 1, informed them that other participants from Prolific had observed their real score and given them advice against which group to compete against, and finally were reminded them of how many questions they guessed they had answered correctly. Importantly, they were not informed of their true score or the score of the groups they could compete against. Participants then observed the advice from a randomly selected adviser and made their decision.</p>
</section>
<section id="results-2" class="level2">
<h2 data-anchor-id="results-2">Results</h2>
<p>We begin by examining the performance of the Stage 1 participants. Because our treatment takes place after participants completed the mathematics quiz, we would not expect a difference in performance across the Low and High Expectations treatments. Indeed, the two groups scored no different from one another (4.79 and 4.55 for the Low Expectations and High Expectations treatments, respectively, <span class="math inline">t(998) = -1.64</span>, <span class="math inline">p = .102</span>). The expectations treatment did, however, affect how well they thought they performed. Participants in the “Low Expectations” treatment guessed a score of 4.79 vs. 4.42 in the High Expectations treatment (<span class="math inline">t(998) = 3.78</span>, <span class="math inline">p &lt; .001</span>), showing that the manipulation was successful, albeit small. Contrary to our expectations, we did find a gender difference in performance: men scored 5.02 on average, while women scored 4.33 (<span class="math inline">t(998) = -4.73</span>, <span class="math inline">p &lt; .001</span>). Consistent with this difference, men thought they answered more questions correctly than did women (4.75 vs 3.56, <span class="math inline">t(998) = -8.60</span>, <span class="math inline">p &lt; .001</span>). This difference, however, does not affect the interpretation of our findings, which will rely on an interaction of gender with an experimental treatment for Stage 2 participants.</p>
<p>We define a measure of “overconfidence” as (Performance - Estimate). We observe that women underestimate their performance by 0.76 points, while men do so by only 0.27 points <span class="math inline">\Delta M = -0.49</span>, 95% CI <span class="math inline">[-0.73, -0.25]</span>, <span class="math inline">t(997.87) = -4.03</span>, <span class="math inline">p &lt; .001</span>. Although neither gender is overconfident, men on average are more confident in their performance than are women, as we had expected.</p>
<div class="cell FigureWithoutNote" data-layout-align="center" prefix="" data-tblnum="3" data-custom-style="FigureWithoutNote">
<div id="tbl-study3regs" class="cell quarto-float quarto-figure quarto-figure-center" data-layout-align="center" prefix="" data-tblnum="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-study3regs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Column 1 displays the advice given to compete against a High Performance group based on whether the advisees were primed with low or high expectations and the expectation level shown to the advisor. Column 2 displays the advice given to compete against a High Performance group based on the gender of the targets and the expectation level shown to the advisor. Column 3 displays the expected bonus of the advice received based on the gender of the targets and the expectation level shown to the advisor. All standard errors clustered at the level of the advisor.</p>
</div>
</figcaption>
<div aria-describedby="tbl-study3regs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(2)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High Expectation</td>
<td style="text-align: center;">0.012</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.011)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Performance</td>
<td style="text-align: center;">0.128***</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.003)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expectation Shown</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.034*</td>
<td style="text-align: center;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.013)</td>
<td style="text-align: center;">(0.003)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Advisee Male</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.002</td>
<td style="text-align: center;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.005)</td>
<td style="text-align: center;">(0.001)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expectation x Male</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.032***</td>
<td style="text-align: center;">−0.005**</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.009)</td>
<td style="text-align: center;">(0.002)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: center;">−0.263***</td>
<td style="text-align: center;">0.339***</td>
<td style="text-align: center;">0.258***</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.015)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.010)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.002)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: center;">5000</td>
<td style="text-align: center;">10000</td>
<td style="text-align: center;">10000</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell FigureWithoutNote" data-layout-align="center" data-custom-style="FigureWithoutNote">
<div class="cell-output-display">
<div id="fig-study3genderdiff" class="quarto-float quarto-figure quarto-figure-center" data-fignum="5" prefix="" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-study3genderdiff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;5</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Advisers observed real performance and the participants’ estimated performance, but not their gender. As a result of their higher expectations, men (blue) were advised to compete against the high performance group more often than women (red). The grey line shows advice absent expectations, which did not differ by gender.</p>
</div>
</figcaption>
<div aria-describedby="fig-study3genderdiff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_files/figure-html/fig-study3genderdiff-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
</figure>
</div>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>Next, we examine whether advisers took the advisee’s expectations into account. Column 1 of <a href="#tbl-study3regs" class="quarto-xref" aria-expanded="false">Table&nbsp;3</a> reports a linear probability model on advising to compete against the High Performer group for advisers in the “Expectations” treatment, controlling for the true performance of the advisee. Because each adviser made ten recommendations, we cluster standard errors at the adviser level. However, contrary to our expectations, we do not see a significant effect of the expectations treatment. This may be because the induced difference in expectations was too small.</p>
</div>
<p>However, recall that men were more confident in their performance than were women. Our theory thus predicts that showing expectations should lead to more flattering advice (i.e., a recommendation to compete against the High Performer group) for men than for women. We report a linear probability model with advice to compete against the high group as the outcome measure, and the advisee’s gender, whether expectations were shown to the adviser, and the interaction of the two in Column 2 of <a href="#tbl-study3regs" class="quarto-xref" aria-expanded="false">Table&nbsp;3</a>. As predicted, we find a significant interaction effect: men are more likely to be advised to compete against the High Performers when expectations are shown than when they are hidden (<span class="math inline">p &lt; 0.001</span>). We show this result graphically in <a href="#fig-study3genderdiff" class="quarto-xref" aria-expanded="false">Figure&nbsp;5</a>.</p>
<p>To examine the quality of advice, we computed the expected bonus earnings for someone who followed the recommendations. For example, if an adviser suggested competing against the High Performer group, we matched the advisee against all 20 members of that group and determined how often their score matched or exceeded that of the member. We then multiplied this number by the respective bonus earnings (50 cents and 30 cents for the High and Low Performer group, respectively). To see if including expectations leads to worse advise for men, we report a linear probability model with the experimental treatment of the adviser, the gender of the advisee, and their interaction in Column 3 of <a href="#tbl-study3regs" class="quarto-xref" aria-expanded="false">Table&nbsp;3</a>. Displaying expectations led men to be advised to compete against the High Performer group more often, and this advise turned out to be bad: men receive worse advise than do women when expectations are displayed, but not in their absence.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell FigureWithoutNote" data-layout-align="center" prefix="" data-tblnum="4" data-custom-style="FigureWithoutNote">
<div id="tbl-study3time3" class="cell quarto-float quarto-figure quarto-figure-center" data-layout-align="center" prefix="" data-tblnum="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-study3time3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;4</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Column 1 displays the actual bonus based on the performance and whether the participant is primed with high expectations. Column 2 displays the actual bonus based on the performance and gender of the participant. Columns 3 and 4 display the chance of adopting the advice based on the gender of the participants, whether the advisee sees expectations, and whether the advice is to compete against high performers. The former considers only the main effect, while the latter also includes the interactive effect.</p>
</div>
</figcaption>
<div aria-describedby="tbl-study3time3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(2)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(3)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;&nbsp;(4)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Performance</td>
<td style="text-align: center;">0.038***</td>
<td style="text-align: center;">0.039***</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.003)</td>
<td style="text-align: center;">(0.003)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">High Expectation</td>
<td style="text-align: center;">−0.020</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.013)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Advisee Male</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.002</td>
<td style="text-align: center;">−0.045+</td>
<td style="text-align: center;">−0.144***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.013)</td>
<td style="text-align: center;">(0.026)</td>
<td style="text-align: center;">(0.041)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expectation x Male</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.113*</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.053)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expectation Shown</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.002</td>
<td style="text-align: center;">−0.057</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.026)</td>
<td style="text-align: center;">(0.040)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Advice: High Performer</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.138***</td>
<td style="text-align: center;">−0.207***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.028)</td>
<td style="text-align: center;">(0.051)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Advice: High Performer x Male</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.131*</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.056)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expectation x Advice: High Performer</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.009</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.056)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Constant</td>
<td style="text-align: center;">0.087***</td>
<td style="text-align: center;">0.076***</td>
<td style="text-align: center;">0.857***</td>
<td style="text-align: center;">0.906***</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.016)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.015)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.024)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.030)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: center;">483</td>
<td style="text-align: center;">483</td>
<td style="text-align: center;">951</td>
<td style="text-align: center;">951</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>To determine whether flattering advice is truly costly, however, we need to examine the outcome of the advisees. In particular, they could ignore flattering advice, recognizing it as such and thus failing to adhere to it. Align with our prediction, participants who were primed with high expectations earned less when their expectations were conveyed to the advisers, although this result is only directional (see Column 1 of <a href="#tbl-study3time3" class="quarto-xref" aria-expanded="false">Table&nbsp;4</a>). Similarly, as shown in Column 2 of <a href="#tbl-study3time3" class="quarto-xref" aria-expanded="false">Table&nbsp;4</a>, we also found that male participants received less reward when their expectations were presented, even when their performance was the same. These findings suggest that flattering advice is not without consequences. Furthermore, our research indicates that because males are more likely to follow such advice (see Column 4 of <a href="#tbl-study3time3" class="quarto-xref" aria-expanded="false">Table&nbsp;4</a>), their tendency towards competition intensifies the cost of such advice.</p>
</div>
</section>
<section id="discussion-2" class="level2">
<h2 data-anchor-id="discussion-2">Discussion</h2>
<p>We found supportive evidence for our argument in a different domain. Advisors tend to consider advisees’ self-expectations and match their advice accordingly, aiming to avoid disappointment. Consistent with the confidence gap narrative, men tend to underestimate their mathematics test scores less than women. When these expectations are displayed to advisors, they are more likely to advise men to compete against high performers. Notably, this turns out to be poor advice: men whose advisors were aware of their expectations received worse advice. Our findings suggest that men with the same scores as their female counterparts ended up earning less, although this result is only directional. This discrepancy may be due to men receiving more favorable advice, being more likely to follow it, and ultimately facing worse outcomes.</p>
<!-- David: One more sentence about the earnings difference here, which does not -->
<!-- differ significantly. And one sentence about the new analysis of whether -->
<!-- people follow the advice or not. -->
</section>
</section>
<section id="general-discussion" class="level1">
<h1>General Discussion</h1>
<p>Advice has the potential to shape people’s career and personal outcomes. Honest feedback, however, may be painful to learn if it falls short of one’s expectations. As prior work notes, this may motivate people to avoid information and avoid seeking help <span class="citation" data-cites="Benabou2022 Golman2017 Jaroszewicz2022">(Bénabou et al., 2022; Golman et al., 2017; Jaroszewicz et al., 2021)</span>. We present evidence from two experiments that advisers are also cognizant of this cost. As a result, they present flattering advice that avoids disappointing the recipient, and correctly anticipate that this boosts how advisees perceive them. However, this flattering advice comes at a cost to advisees, who would do worse if they followed it blindly, as we show in Study 1.</p>
<p>Moreover, a desire to avoid disappointment also means that advisers have to take into account the expectations of the advisee. We document that men are more optimistic about their performance than women are. As a result, they receive more flattering advice and are more likely to be told to aim higher. Notably, in the context of our experiment, this turns out to be bad advice ex post.</p>
<p>Our findings have implications for organizational practice, where mentoring and advice-giving may take into account an employees’ expectation. We document this as a novel source of gender bias. Organizations could reduce this bias by calibrating employees’ expectations to reduce overconfidence.</p>
<p>Participants in our experiment were paired anonymously. Even so, we document this desire to avoid disappointment. We anticipate that advice would be more flattering in face-to-face communication and without anonymity. Moreover, existing relationships might make it even more difficult for advisers to be honest.</p>
<p>In our experiments, participants only received advice once and did not evaluate the adviser after observing the outcome of their decision. For example, advice that leads to bad outcomes may undermine the interpersonal benefits of flattery. Alternatively, people may still like the flattering advice and not fault the adviser for the bad outcome. Moreover, our setting involved only a single piece of advice on one task. Future research could examine whether people return to those who gave them flattering advice, or if they prefer someone who gave them the honest (but unpleasant) truth.</p>
<p>Advice has long been studied from the perspective of the receiver. Similarly, research on belief utility has examined how recipients respond to the valence of the information they receive. Here, we show that advisers, too, take into account the psychological impact of the information they convey. They may have even greater motivations to avoid conveying bad news, because they incur the interpersonal costs of delivering unfavorable information without reaping the benefits from helping someone make a better choice.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Greenwald1995" class="csl-entry" role="listitem">
Banaji, M. R., &amp; Greenwald, A. G. (1995). Implicit gender stereotyping in judgments of fame. <em>Journal of Personality and Social Psychology</em>, <em>68</em>(2), 181.
</div>
<div id="ref-Benabou2022" class="csl-entry" role="listitem">
Bénabou, R., Jaroszewicz, A., &amp; Loewenstein, G. (2022). <em>It <span>Hurts</span> to <span>Ask</span></em>. National Bureau of Economic Research.
</div>
<div id="ref-Chang2019" class="csl-entry" role="listitem">
Chang, E. H., Milkman, K. L., Gromet, D. M., Rebele, R. W., Massey, C., Duckworth, A. L., &amp; Grant, A. M. (2019). The mixed effects of online diversity training. <em>Proceedings of the National Academy of Sciences</em>, <em>116</em>(16), 7778–7783.
</div>
<div id="ref-Fiske2007" class="csl-entry" role="listitem">
Fiske, S. T., Cuddy, A. J., &amp; Glick, P. (2007). Universal dimensions of social cognition: Warmth and competence. <em>Trends in Cognitive Sciences</em>, <em>11</em>(2), 77–83.
</div>
<div id="ref-Gino2007" class="csl-entry" role="listitem">
Gino, F., &amp; Moore, D. A. (2007). Effects of task difficulty on use of advice. <em>Journal of Behavioral Decision Making</em>, <em>20</em>(1), 21–35.
</div>
<div id="ref-Golman2017" class="csl-entry" role="listitem">
Golman, R., Hagmann, D., &amp; Loewenstein, G. (2017). Information avoidance. <em>Journal of Economic Literature</em>, <em>55</em>(1), 96–135. <a href="https://doi.org/10.1257/jel.20151245">https://doi.org/10.1257/jel.20151245</a>
</div>
<div id="ref-Hagmann2024" class="csl-entry" role="listitem">
Hagmann, D., Sajons, G. B., &amp; Tinsley, C. H. (2024). <em>Base rate neglect as a source of inaccurate statistical discrimination</em>.
</div>
<div id="ref-Harvey1997" class="csl-entry" role="listitem">
Harvey, N., &amp; Fischer, I. (1997). Taking advice: <span>Accepting</span> help, improving judgment, and sharing responsibility. <em>Organizational Behavior and Human Decision Processes</em>, <em>70</em>(2), 117–133.
</div>
<div id="ref-Ho2018" class="csl-entry" role="listitem">
Ho, E. H., Hagmann, D., &amp; Loewenstein, G. (2021). Measuring information preferences. <em>Management Science</em>, <em>67</em>(1), 126–145.
</div>
<div id="ref-Jaroszewicz2022" class="csl-entry" role="listitem">
Jaroszewicz, A., Loewenstein, G., &amp; Bénabou, R. (2021). <em>The pain of asking and being asked for informal help</em>.
</div>
<div id="ref-John2019" class="csl-entry" role="listitem">
John, L. K., Jeong, M., Gino, F., &amp; Huang, L. (2019). The self-presentational consequences of upholding one’s stance in spite of the evidence. <em>Organizational Behavior and Human Decision Processes</em>, <em>154</em>, 1–14.
</div>
<div id="ref-Kanze2018" class="csl-entry" role="listitem">
Kanze, D., Huang, L., Conley, M. A., &amp; Higgins, E. T. (2018). We ask men to win and women not to lose: <span>Closing</span> the gender gap in startup funding. <em>Academy of Management Journal</em>, <em>61</em>(2), 586–614.
</div>
<div id="ref-Koszegi2006" class="csl-entry" role="listitem">
Kőszegi, B., &amp; Rabin, M. (2006). A model of reference-dependent preferences. <em>The Quarterly Journal of Economics</em>, <em>121</em>(4), 1133–1165.
</div>
<div id="ref-Koszegi2009" class="csl-entry" role="listitem">
Kőszegi, B., &amp; Rabin, M. (2009). Reference-dependent consumption plans. <em>American Economic Review</em>, <em>99</em>(3), 909–936.
</div>
<div id="ref-Loewenstein2018" class="csl-entry" role="listitem">
Loewenstein, G., &amp; Molnar, A. (2018). The renaissance of belief-based utility in economics. <em>Nature Human Behaviour</em>, <em>2</em>(3), 166–167.
</div>
<div id="ref-Greenwald2009" class="csl-entry" role="listitem">
Nosek, B. A., Smyth, F. L., Sriram, N., Lindner, N. M., Devos, T., Ayala, A., Bar-Anan, Y., Bergh, R., Cai, H., Gonsalkorale, K., et al. (2009). National differences in gender–science stereotypes predict national sex differences in science and math achievement. <em>Proceedings of the National Academy of Sciences</em>, <em>106</em>(26), 10593–10597.
</div>
<div id="ref-Paluck2009" class="csl-entry" role="listitem">
Paluck, E. L., &amp; Green, D. P. (2009). Prejudice reduction: What works? A review and assessment of research and practice. <em>Annual Review of Psychology</em>, <em>60</em>, 339–367.
</div>
<div id="ref-Shalvi2019" class="csl-entry" role="listitem">
Shalvi, S., Soraperra, I., Weele, J. J. van der, &amp; Villeval, M. C. (2019). <em>Shooting the messenger? Supply and demand in markets for willful ignorance</em>.
</div>
<div id="ref-Soll2009" class="csl-entry" role="listitem">
Soll, J. B., &amp; Larrick, R. P. (2009). Strategies for revising judgment: How (and how well) people use others’ opinions. <em>Journal of Experimental Psychology: Learning, Memory, and Cognition</em>, <em>35</em>(3), 780.
</div>
</div>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>This shading could be due to concerns of avoiding disappointment. However, it could also be that advisers are uncertain about the rankings they had given and make a recommendation that combines their own belief with a uniform prior.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>We made this decision to account for the possibility of gender differences in performance.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>This analysis was not preregistered, and we note here that the reduction in expected earnings is small. However, it is interesting that expectations have a negative effect for men who underestimate their performance on average. One possibility is that advisers suggest the High Performer group more often than is optimal. We return to the possibility that advice is overall biased to be flattering in Study 2.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>